### ISSUE TITLE
No Value Support

### ISSUE THREAD

**Issue by kaendfinger** [just95/toml.dart#1]
I recall that TOML has support for a null value by not providing a value, but in my experience, I was not able to parse a document with it.
```toml
broadcast = false
brokerName = "broker-"
certName = ""
certPassword = ""
debug = false
defaultPermission =
disableFileSecurity = false
disabledLinks = []
httpsport = 8443
loginRedirectPath = "/"
passwordHasherIterations = 1000
passwordHasherKeyLength = 32
port = 8080
quarantine = false
runBrokerInMain = false
updateInterval = 200
uptimeCheckUrl =
useRuntimeManager = false
workers = 2
```
